# Generated by Django 4.1.2 on 2022-10-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cotmodel',
        ),
    ]
