# Generated by Django 3.1.14 on 2022-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsapp', '0002_delete_cotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='orphanage_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('aadhaar_no', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('DOB', models.CharField(max_length=200, null=True)),
                ('photo', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
