# Generated by Django 3.1.14 on 2022-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsapp', '0003_auto_20221105_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='orphanagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=200, null=True)),
                ('owner_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orphanage_user',
            old_name='photo',
            new_name='img',
        ),
    ]
