# Generated by Django 3.1.14 on 2022-11-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsapp', '0004_auto_20221105_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='donationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('Orphanagename', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
